Repository invertase/globe, pull requests merged in 2024-12, with the labels that each got.

#117 feat: Multi project linking via CLI
  packages/globe_cli/lib/src/command_runner.dart
  packages/globe_cli/lib/src/commands/build_logs_command.dart
  packages/globe_cli/lib/src/commands/deploy_command.dart
  packages/globe_cli/lib/src/commands/link_command.dart
  packages/globe_cli/lib/src/commands/project/project_pause_command.dart
  packages/globe_cli/lib/src/commands/project/project_resume_command.dart
  packages/globe_cli/lib/src/commands/token/token_delete_command.dart
  packages/globe_cli/lib/src/commands/token/token_list_command.dart
  packages/globe_cli/lib/src/commands/unlink_command.dart
  packages/globe_cli/lib/src/utils/api.dart
  packages/globe_cli/lib/src/utils/prompts.dart
  packages/globe_cli/lib/src/utils/scope.dart
  packages/globe_cli/pubspec.lock
  packages/globe_cli/pubspec.yaml
Labels: enhancement

#120 docs: Terms of service and privacy policy page
  docs.json
  docs/terms-privacy/index.mdx
  docs/terms-privacy/privacy-policy.mdx
  docs/terms-privacy/terms-of-service.mdx
Labels: documentation

#123 fix: Resolve main entry path relative to project directory
  packages/globe_cli/lib/src/utils/logs.dart
  packages/globe_cli/lib/src/utils/prompts.dart
Labels: enhancement

#125 chore: Pass org if already selected
  packages/globe_cli/lib/src/package_info.dart
  packages/globe_cli/lib/src/utils/prompts.dart
  packages/globe_cli/lib/src/utils/scope.dart
Labels: bug
